import { Column, Index, Model, Table } from 'disbord';

@Table('notice_channels')
export class NoticeChannel extends Model<NoticeChannel.Data> {
  @Column('text')
  @Index()
  accessor guildId!: string;

  @Column('text')
  accessor channelId!: string;
}

// AUTO-GENERATED by disbord. Do not edit below this line — regenerated by `disbord generate model` / `disbord migrate` / `disbord model type`.
export namespace NoticeChannel {
  export type Data = { guildId: string; channelId: string };
}
