import { Column, Model, Table } from 'disbord';
import { omikuji, type Omikuji } from '@/db/models/User';

@Table('totals')
export class Total extends Model<Total.Data> {
  @Column('integer', { default: 0 })
  accessor kira!: number;

  @Column('integer', { default: 0 })
  accessor yoshida!: number;

  @Column('integer', { default: 0 })
  accessor daikichi!: number;

  @Column('integer', { default: 0 })
  accessor chukichi!: number;

  @Column('integer', { default: 0 })
  accessor kichi!: number;

  @Column('integer', { default: 0 })
  accessor syokichi!: number;

  @Column('integer', { default: 0 })
  accessor suekichi!: number;

  @Column('integer', { default: 0 })
  accessor kyo!: number;

  @Column('integer', { default: 0 })
  accessor daikyo!: number;

  private static get data() {
    return this.find().then((data) => data ?? this.create({}));
  }

  public static get resultEntries() {
    return this.data.then(
      (data) => (Object.keys(omikuji) as Omikuji[]).map((key) => [key, data[key]]) as [Omikuji, number][],
    );
  }

  public static async increment(omikuji: Omikuji) {
    const data = await this.data;
    await data.update({ [omikuji]: data[omikuji] + 1 });
  }
}

// AUTO-GENERATED by disbord. Do not edit below this line — regenerated by `disbord generate model` / `disbord migrate` / `disbord model type`.
export namespace Total {
  export type Data = {
    kira?: number;
    yoshida?: number;
    daikichi?: number;
    chukichi?: number;
    kichi?: number;
    syokichi?: number;
    suekichi?: number;
    kyo?: number;
    daikyo?: number;
  };
}
