services:
  yoshida-bot:
    build: .
    container_name: coyote-bot
    restart: always
    environment:
      TOKEN: ${TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      YOSHIDA_USER_ID: ${YOSHIDA_USER_ID}
      MONGO_URI: ${MONGO_URI}
      DB_NAME: ${DB_NAME}
      TEST_GUILD_ID: ${TEST_GUILD_ID}
      TEST_CHANNEL_ID: ${TEST_CHANNEL_ID}
    volumes:
      - ${HOLIDAYS_PATH}:/app/holidays.json
