// AUTO-GENERATED by `disbord migrate`. Do not edit — regenerated on every `disbord migrate` run.
import { buildSchema, buildTable } from 'disbord';
import { NoticeChannel } from '@/db/models/NoticeChannel';
import { Result } from '@/db/models/Result';
import { Total } from '@/db/models/Total';
import { User } from '@/db/models/User';

export const noticeChannel = buildTable(NoticeChannel);
export const result = buildTable(Result);
export const total = buildTable(Total);
export const user = buildTable(User);

export const schema = buildSchema([noticeChannel, result, total, user]);
